version: "3.9"

services:
  hello-frontend:
    image: hello-frontend
    ports:
      - 5000:5000
  hello-backend-redis:
    image: hello-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:latest
